#!/usr/bin/env python3
import os
import re
import sys
import subprocess

def print_log(msg):
    print(f"[*] 🤖 [Chigura Scout] {msg}")

def run_gemini(prompt, system_instruction=""):
    full_prompt = prompt
    if system_instruction:
        full_prompt = f"System: {system_instruction}\n\nUser: {prompt}"
    
    agy_path = os.path.expanduser("~/.local/bin/agy")
    if not os.path.exists(agy_path):
        agy_path = "agy"
        
    cmd = [agy_path, "-p", full_prompt]
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
        stdout_clean = re.sub(r'\x1b\[[0-9;]*m', '', proc.stdout)
        return stdout_clean.strip()
    except Exception as e:
        print_log(f"❌ Gemini Error: {e}")
        return None

def main():
    print_log("Starting self-scouting for new ideas (Powered by Gemini)...")
    
    readme_path = "/home/mayutama/workspace/need-this-to-exist/README.md"
    if not os.path.exists(readme_path):
        print_log("❌ README.md not found.")
        return
        
    with open(readme_path, "r", encoding="utf-8") as f:
        readme_content = f.read()
        
    # 最新のアイデアのインデックスを特定
    index_matches = re.findall(r'### (\d+)\.', readme_content)
    last_index = int(index_matches[-1]) if index_matches else 0
    next_index = last_index + 1
    
    # ちぐら（AI）へのリサーチ命令
    scout_prompt = f"""
あなたは自律型アイデア収集Botの「ちぐら」です。
海外のReddit (/r/SomebodyMakeThis, /r/SideProject) やIndie Hackers、Twitterなどでギークたちが不満を漏らしている「作れるのに世の中にないニッチな製品やガジェット、ブラウザ拡張機能」のアイデアをWebから探し出すか、あるいは強力に推論して1件提案してください。

以下の「現在のアイデアリスト」にすでにあるもの（あるいは極めて似たアイデア）は絶対に避けてください。
完全新規のアイデアである必要があります。

【現在のアイデアリスト】:
{readme_content}

インデックス番号 {next_index} 番として、以下のマークダウン形式（日本語）で厳密に1件だけ出力してください。余計な前置きや「はい、了解しました」などの後書きは一切不要です：

### {next_index}. [日本語で付けた魅力的な製品名] ([英語の製品名])
*   **Category**: [Hardware / Software / Browser Extension など適したカテゴリ]
*   **Pain Point**: [ユーザーの具体的な悩みや課題（日本語でわかりやすく要約）]
*   **Solution**: [AIが提案する具体的なソリューション（日本語）]
*   **Why it doesn't exist**: [なぜ今ちょうど良いものが市販・公開されていないのかの分析]
*   **Status**: 💡 Idea (パトロン・開発者募集中)
*   **🛠️ DIY Recipe (自分で作るレシピ)**: [※もしラズパイやESP32等のマイコン、あるいはPython/Node.js等の主要なOSSライブラリを使ってDIYで自作可能な場合のみ、推奨パーツリスト、簡易配線、および15行以内のシンプルなサンプルコード（CircuitPythonやPython等）をここに詳しく記載してください。非DIY型の場合はこの項目自体を省略するか『※非DIY製品』と簡潔に記載してください。]
"""
    
    print_log("Scouting the web for niche pain points...")
    result = run_gemini(scout_prompt)
    
    if not result or "###" not in result:
        print_log("❌ Failed to generate a valid new idea.")
        return
        
    # 重複やフォーマット不備の最終チェック
    # (稀にインデックス番号が正しく出力されない場合があるため修正)
    if not result.startswith(f"### {next_index}."):
        # もし ### 1. などのように別の番号で始まっていたら置換する
        result = re.sub(r'^### \d+\.', f"### {next_index}.", result)
        
    print_log(f"✅ Found new awesome idea: {result.splitlines()[0]}")
    
    # README.mdを更新
    insertion = "\n\n" + result + "\n\n"
    updated_content = readme_content.replace("\n\n## 🤖 Generated by Chigura", insertion + "## 🤖 Generated by Chigura")
    
    with open(readme_path, "w", encoding="utf-8") as f:
        f.write(updated_content)
        
    print_log("🎉 README.md successfully updated with the new idea!")
    
    # Git自動コミット
    if os.path.exists(os.path.join(os.path.dirname(readme_path), ".git")):
        try:
            # 最新の追加部分からタイトルだけ抽出してコミットメッセージにする
            title_line = result.splitlines()[0].replace(f"### {next_index}. ", "")
            subprocess.run(["git", "add", "README.md"], cwd=os.path.dirname(readme_path))
            subprocess.run(["git", "commit", "-m", f"Auto: Add '{title_line}' scouted by Chigura"], cwd=os.path.dirname(readme_path))
            print_log("Git commit complete.")
        except Exception as e:
            print_log(f"Git commit failed: {e}")

if __name__ == "__main__":
    main()
